site_name: DSMRloggerWS
site_url: https://willem.aandewiel.nl/index.php/2019/04/09/dsmr-logger-v4-slimme-meter-uitlezer/
site_description: DSMRloggerWS documentation with mkdocs.
site_author: Willem Aandewiel

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml

nav:
    - Introductie: 'index.md'
    - bouwbeschrijving: 'bouwbeschrijvingV4.md'
    - Installatie ArduinoIDE: 'installatieArduinoIDE.md'
    - Installatie Bibliotheken: 'installatieBibliotheken.md'

    - Firmware:
       - Clonen van github: 'clonenFirmware.md'
       - Uploaden naar ESP-01: 'uploadenFirmware.md'
       - Upload Data ESP-01: 'uploadenDataMap.md'
       - Eerste keer opstarten: 'eersteKeerOpstarten.md'
    - Verschillen ESP-01 modules: 'verschillenESP01ESP01S.md'

