site_name: DSMRloggerWS
site_url: https://willem.aandewiel.nl/index.php/2018/08/28/slimme-meter-uitlezer/
site_description: Project documentation with Markdown.
site_author: Willem Aandewiel
copyright: 'copyright &copy; 2019 <a href="https://willem.aandewiel.nl/index.php/2019/04/09/dsmr-logger-v4-slimme-meter-uitlezer/">Willem Aandewiel</a>'


extra_css: 
    - extra.css

theme:
    name: readthedocs
    theme.prev_next_buttons_location: 'both'
    config.theme.titles_only: true
    highlightjs: true
    hljs_languages:
        - yaml

nav:
    - 'index.md'
    - 'introductie.md'

    - Voorbereiding:
       - 'ArduinoIDE': 'installatieArduinoIDE.md'
       - 'ESP8266 Core': 'installatieESP8266core.md'
       - 'Data Upload Tool': 'installatieDataUploadTool.md'
       - 'Installeren Bibliotheken': 'installatieBibliotheken.md'

    - Firmware:
       - 'Benodigd Bibliotheken': 'benodigdeBibliotheken.md'
       - 'DSMRloggerWS firmware': 'clonenFirmware.md'
       - 'Firmware Flashen DSMR-logger v4': 'uploadFirmware_V4.md'
       - 'Data Flashen DSMR-logger v4': 'uploadDataMap_V4.md'
       - 'Firmware Flashen DSMR-logger v3': 'uploadFirmware_V3.md'
       - 'Data Flashen DSMR-logger v3': 'uploadDataMap_V3.md'

    - Hardware:
       - 'DSMR-logger v4': 'hardware_V4.md'
       - 'Programmer DSMR-logger v4': 'hardware_V4_Programmer.md'
       - 'DSMR-logger v3': 'hardware_V3.md'
       - 'Programmer DSMR-logger v3': 'hardware_V3_Programmer.md'


    - Overigen:
       - (eerste keer) Opstarten: 'Opstarten.md'
       - restAPI: 'restAPI.md'
       - Verschillen ESP8266 modules: 'verschillenESP8266.md'
       - Over The Air (bug?): 'uploadOTA-bug.md'
       - PUYA chips: 'PUYA_patch.md'
       - Integratie Domoticz: 'integratieDomoticz.md'
       - Vragen en Antwoorden: 'QenA.md'

    - License: 'MITlicense.md'

