site_name: DSMRloggerWS
site_url: https://willem.aandewiel.nl/index.php/2018/08/28/slimme-meter-uitlezer/
site_description: Project documentation with Markdown.
site_author: Willem Aandewiel

extra_css: 
    - extra.css

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml

nav:
    - 'index.md'

    - Voorbereiding:
       - 'ArduinoIDE': 'installatieArduinoIDE.md'
       - 'ESP8266 Core': 'installatieESP8266core.md'
       - 'Data Upload Tool': 'installatieDataUploadTool.md'

    - Firmware:
       - 'Benodigd Bibliotheken': 'benodigdeBibliotheken.md'
       - 'Installeren Bibliotheken': 'installatieBibliotheken.md'
       - 'DSMR-Firmware': 'clonenFirmware.md'
       - 'Firmware Flashen naar ESP-01': 'uploadFirmware_ESP-01.md'
       - 'Data Flashen naar ESP-01': 'uploadDataMap_ESP-01.md'
       - 'Firmware Flashen naar DSMRlogger v4': 'uploadFirmware_ESP-12.md'
       - 'Data Flashen naar DSMRlogger v4': 'uploadDataMap_ESP-12.md'

    - Hardware:
       - 'DSMRlogger v3': 'hardware_V3.md'
       - 'DSMRlogger v4': 'hardware_V4.md'
       - 'Programmer ESP-01': 'hardware_ESP01_Programmer.md'
       - 'Programmer DSMRlogger v4': 'hardware_DSMR_Programmer.md'

    - Verschillen ESP8266 modules': 'verschillenESP8266.md'

